name: Medium article workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 */12 * * *' # Runs every 12 hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://sagar0-0.medium.com/feed"
          # feed_list: "https://sagar0-0.hashnode.dev/rss.xml"
          max_post_count: 2
          custom_tags: "postImage/cover_image/"
          template: '<table><tr><td><a href="$url"><img width="140px" src="$postImage"></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
